modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
issueTrackerURL = "https://github.com/gen1nya/minecraft-admin-bukkit-plugin/issues"

[[mods]]
modId = "webadminplugin"
version = "${file.jarVersion}"
displayName = "WebAdminPlugin"
authors = "Admin"
displayTest = "IGNORE_SERVER_VERSION"
description = '''
Server administration plugin providing /playerlist and /serverstat commands.
Returns player information and server statistics in JSON format.
'''

[[dependencies.webadminplugin]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.webadminplugin]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "SERVER"
